'ユーザーデータがたまってるデータベースにリクエストしてレスポンスが帰ってきてワールドに変化があるところまで
'clean architectureベースで

@startuml
package Presentation
{
    package View
    {
        class UsersTable << MonoBehaviour >>
        {
            - userCells: UserCell[]
        }
        
        class UserCell << MonoBehaviour >>
        {
            
        }
    }
    
    package Presenter
    {
        class UserPresenter
        {
            - userUseCase: UserUseCase
            - usersTable: UsersTable
            
            + LoadUsers()
        }
    }
    
    Presenter -down- View
    Presenter -right- UseCase
}

package Domain
{
    package Model
    {
        class UserModel
        {
            id: int
            name: string
            money: int
        }
        
        class UsersModel
        {
            users: UserModel[]
        }
    }
    
    package Translator
    {
        class UserTranslator <<static>>
        {
            + {static} Translate(userEntities: IEnumerable<UserEntity>)
        }
    }
    
    package UseCase
    {
        class UserUseCase
        {
            - userRepository: UserRepository
            + LoadUsers()
        }
    }
    
    package Repository
    {
        class UserRepository
        {
            - userDataStore: UserDataStore
            + GetUsers()
        }
    }
    
    UseCase -down- Translator
    Translator -down- Model
    UseCase -right- Repository
    Repository -right- DataStore
}

package Data
{
    package DataStore
    {
        class UserDataStore
        {
            + GetUsers()
        }
    }
    
    package Entity
    {
        class UserEntity << struct >>
        {
            id: int
            name: string
            money: int
        }
    }
    
    DataStore -down- Entity
}

@enduml